# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-12 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trippicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippicture',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
